### PR TITLE
Set up tests for  each component 

### PR DESCRIPTION
**Pull request by shaima96**
release to #37

### CODE REVIEW

**Comment by shaima96** [comment]
We need to make folder snapshots for every component, but  I don't understand what the benefit of making it? 
@teenie-quaggard 
I saw that from the previos project in `founder-program-2` and make as it.

**Comment by teenie-quaggard** [comment]
@shaima96 
react snapshot testing means that a 'snapshot' of each component is taken. any changes will be compared to that snapshot so that you can see if you have made any unintended changes. before making a pr, you would update your snapshots so you would always compare to an 'approved' copy of the project.

https://jestjs.io/docs/en/snapshot-testing

let's talk about this at standup. snapshot testing is not tdd but we haven't really been working tdd anyways...

**Comment by shaima96** [comment]
I saw some docs but is not clear perfectly.
So I asked Mohammed who worked in `howl` project, he told me should put the script for snapshots.
@teenie-quaggard

**Comment by teenie-quaggard** [comment]
added one commit where i tested that snapshots were working and updated package-lock

approved! 
let's @founders-programme-2/business-launchpad all remember to run the snapshot update file before every pr :)

**Pull request merged**
