### PR TITLE
Feature/database data setup

### PR DESCRIPTION
**Pull request by teenie-quaggard**
Implements logout and token checking functionality
Relates to #93

### CODE REVIEW

**Comment by SalwaMugh** [comment]
@teenie-quaggard you will need to apply your code on fake data so you can be sure that it's working!

**Comment by SalwaMugh** [comment]
my mentor said postman helps with sending req to the server.
you also need to check if a new user actually got stored in the db

**Comment by SalwaMugh** [comment]
code reviewing [this](https://github.com/FACG5/BounceBack) project will help you with the jwt.

**Comment by teenie-quaggard** [comment]
@SalwaMugh yes, I have been using postman to send requests!
a new user is being stored in the database. 
i have made a few changes in my current branch, but i'll make a pr for that tomorrow. 

thanks for that project link :)

**Pull request merged**
