### PR TITLE
Codecov setup

### PR DESCRIPTION
**Pull request by shaima96**
relate to #55

### CODE REVIEW

**Comment by shaima96** [comment]
I want to be honest with you this first time to make codecov with Travis, I dealt with Travis in the previous projects.
but I saw some documentation about how to did it.
Sorry because it is new to me.

**Comment by shaima96** [comment]
when you want to see what the result for codecov put in the terminal `jest --coverage` @teenie-quaggard

**Comment by shaima96** [comment]
who merge the branch you or me? @teenie-quaggard

**Comment by teenie-quaggard** [comment]
@shaima96 can you provide a link to the docs you followed please?

and whoever open the pr merges it :)
🌸

**Comment by shaima96** [comment]
https://docs.codecov.io/docs
https://www.vogella.com/tutorials/Codecov/article.html
https://github.com/codecov/example-node
https://docs.codecov.io/docs

**Comment by teenie-quaggard** [comment]
thank you :)

**Pull request merged**
